### ISSUE TITLE
Problem with training on macOS  

### ISSUE THREAD

**Issue by Hongbo-Z** [dougsm/ggcnn#44]
I came across a problem when I train GG-CNN on Cornell Dataset on my MacBook Pro (15-inch, 2019)

python train_ggcnn.py --description training_example --network ggcnn --dataset cornell --dataset-path  Cornell_Grasping_Dataset/

INFO:root:Loading Cornell Dataset...
INFO:root:Done
INFO:root:Loading Network...
Traceback (most recent call last):
  File "train_ggcnn.py", line 272, in <module>
    run()
  File "train_ggcnn.py", line 229, in run
    net = net.to(device)
...
raise AssertionError("Torch not compiled with CUDA enabled")

**Comment by dougsm** [comment]
It looks like the code assumes you're training on GPU. You can change https://github.com/dougsm/ggcnn/blob/0c50aa7600e8a30d44c5c85cebd6e3394a81f30e/train_ggcnn.py#L228 

 to "cpu" instead and it should work on your computer, but it will be quite slow to train.
