### ISSUE TITLE
problem with Cornell dataset

### ISSUE THREAD

**Issue by Demoyuge** [dougsm/ggcnn#45]
Traceback (most recent call last):
  File "train_ggcnn.py", line 306, in <module>
    run()
  File "train_ggcnn.py", line 231, in run
    Dataset = get_dataset(args.dataset)
  File "D:\develop\demo_learning\湾大先端院\ggcnn-master\utils\data\__init__.py", line 9, in get_dataset
    raise NotImplementedError('Dataset Type {} is Not implemented'.format(dataset_name))
NotImplementedError: Dataset Type Cornell is Not implemented

**Comment by jdrew1303** [comment]
Hey @Demoyuge 

I think the issue youre facing is that the dataset name is case sensitive. It should be cornell not Cornell.  

Hope this helps. 👍
